server:
  port: 8081

application:
  security:
    jwt:
      secret-key: mySecretKey123456789
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/usersdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    # show-sql: false